global:

nginx-ingress-controller:
  enabled: true

keycloak:
  enabled: true
  postgresql:
    enabled: false #disable the internal database, allowing more config if needed for pgadmin
  externalDatabase:
    host: myexternalhost
    user: myuser
    password: mypassword
    database: mydatabase
    port: 5432
  service:
    type: ClusterIP
    port: 8080 #TODO https
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: keycloak.local
        paths:
          - /auth

postgresql:
  enabled: true

pgadmin4:
  enabled: true
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: pgadmin.local
        paths:
          - /

frontend:
  image:
    registry: localhost:5000
    repository: tributech-ui-oauth-sample
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: frontend.local
        paths:
          - /