keycloak:
  enabled: true
  postgresql:
    enabled: false #disable the internal database, allowing more config if needed for pgadmin
  externalDatabase:
    host: tributech-assignment-postgresql.tributech.svc.cluster.local
    user: keycloak
    password: keycloakpassword
    database: keycloakdb
    port: 5432
  service:
    type: ClusterIP
    port: 8080 #TODO https
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: keycloak.local
        paths:
          - path: /
            pathType: ImplementationSpecific

postgresql:
  auth:
    username: "keycloak"
    password: "keycloakpassword"
    database: "keycloakdb"

pgadmin4:
  enabled: true
  env:
    email: user@example.com
    password: ExtraSuperSecret
  ingress:
    enabled: true
    hosts:
      - host: pgadmin.local
        paths:
          - path: /
            pathType: ImplementationSpecific

frontend:
  image:
    repository: liamfinn/tributech-frontend
    tag: 0.1.0
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    hosts:
      - host: website.local
        paths:
          - path: /
            pathType: ImplementationSpecific