name: 'Push'
on: ['push']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v2'

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: 'Build'
      run: 'helm package .\tributech-assignment-chart\ -u --version "0.1.${{ github.run_number}}"'
    - name: 'Deploy'
      run: 'helm install tributech .\chart-0.1.0.tgz'